"""add description and currency to the user model

Revision ID: 220519338c4d
Revises: cd590ebeb1aa
Create Date: 2026-05-18 09:49:57.857350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '220519338c4d'
down_revision: Union[str, Sequence[str], None] = 'cd590ebeb1aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('description', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('currency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'currency')
    op.drop_column('transactions', 'description')
    # ### end Alembic commands ###
