"""add column age

Revision ID: cd590ebeb1aa
Revises: e68a19ec9214
Create Date: 2026-05-18 09:28:21.977232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd590ebeb1aa'
down_revision: Union[str, Sequence[str], None] = 'e68a19ec9214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('transactions_title_key'), 'transactions', type_='unique')
    op.create_unique_constraint('unique_title_per_user', 'transactions', ['user_id', 'title'])
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age')
    op.drop_constraint('unique_title_per_user', 'transactions', type_='unique')
    op.create_unique_constraint(op.f('transactions_title_key'), 'transactions', ['title'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
