"""initial

Revision ID: e68a19ec9214
Revises: 
Create Date: 2026-05-18 09:23:39.812947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e68a19ec9214'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('transactions_title_key'), 'transactions', type_='unique')
    op.create_unique_constraint('unique_title_per_user', 'transactions', ['user_id', 'title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_title_per_user', 'transactions', type_='unique')
    op.create_unique_constraint(op.f('transactions_title_key'), 'transactions', ['title'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
